# Generated by Django 3.0.5 on 2020-07-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authentiacated_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('localId', models.CharField(max_length=250)),
                ('idToken', models.CharField(max_length=1000)),
                ('refreshToken', models.CharField(max_length=250)),
            ],
        ),
    ]
